### ISSUE TITLE
Recent Projects: reduce visual clutter

### ISSUE THREAD

**Issue by Gama11** [SlavaRa/fdplugin-quicknavigate#119]
When using the "Recent Projects" dialog, I'm mostly interested in the project names. Currently I get something like this:

![](http://i.imgur.com/7gLQ351.png)

The focus here is on the file paths, which I'm not really interested in. I think the name of project should be in front (it's very likely unique anyway), with the path in parens afterwards, slightly greyed out. It would be pretty much perfect if it was done like in the Type Explorer actually:

![](http://i.imgur.com/V3LDU3s.png)

**Comment by SlavaRa** [comment]
UI will be improved in the near future, I'm working on it

**Comment by SlavaRa** [comment]
@Gama11 please check https://github.com/SlavaRa/fdplugin-quicknavigate/releases/tag/2.7.254

**Comment by Gama11** [comment]
Wow, that's a lot nicer. :+1: Make sure to update the `.gif` in the Readme and the version in appman.xml! ;)

**Comment by SlavaRa** [comment]
After #120 )

**Comment by SlavaRa** [comment]
I will update the appman.xml on Saturday
