### ISSUE TITLE
Recent Projects: "open in new window" button

### ISSUE THREAD

**Issue by Gama11** [SlavaRa/fdplugin-quicknavigate#124]
I'm using FD in multi-instance mode, so it would sometimes come in handy to have an "Open in new window" button next to the regular "Open".

That button should probably only be visible if multi-instance mode is enabled.

**Comment by SlavaRa** [comment]
ok, good idea, soon)

**Comment by SlavaRa** [comment]
Done in https://github.com/SlavaRa/fdplugin-quicknavigate/releases/tag/2.8.2
