### ISSUE TITLE
Find All References - add a keyboard shortcut

### ISSUE THREAD

**Issue by gene-pavlovsky** [SlavaRa/fdplugin-quicknavigate#131]
Why isn't there a keyboard shortcut available for Find All References.
All the other features can have shortcuts already, but not this one.

**Comment by SlavaRa** [comment]
In menu -> "Find All References"
In shortcut dialog  -> "SearchMenu.ViewReferences"
But it has nothing to do with the plugin

**Comment by gene-pavlovsky** [comment]
Oh, my bad! I never noticed that option before, until I installed QuickNavigate. Thanks :)
