### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by S-Aoi** [SlavaRa/fdplugin-quicknavigate#34]
![problem](https://cloud.githubusercontent.com/assets/3676278/9731241/57be72b4-564e-11e5-85ef-84f80619c070.png)
Same problem with Type Explorer. My PC's dpi is 150%.

**Comment by SlavaRa** [comment]
Wow, i'll fix it in this week

**Comment by TomByrne** [comment]
I also have this issue when viewing on a retina display.

**Comment by SlavaRa** [comment]
fixed in the latest release
