### ISSUE TITLE
Small typo; resent instead of recent

### ISSUE THREAD

**Issue by markknol** [SlavaRa/fdplugin-quicknavigate#90]
![image](https://cloud.githubusercontent.com/assets/576184/11421193/ac3ec3f2-9433-11e5-8668-38156ce9b3d8.png)

BTW, I really like this plugin! Just saw it was updated the new features are great! Thanks :+1:

**Comment by SlavaRa** [comment]
wow, sorry, i fix it today

**Comment by markknol** [comment]
BTW I especially like the new feature of the type explorer that already lists the open tabs.

**Comment by SlavaRa** [comment]
Fixed in new build https://github.com/SlavaRa/fdplugin-quicknavigate/releases/tag/2.6.4

**Comment by markknol** [comment]
Thanks!
