### ISSUE TITLE
Recent Projects: up down nagivation broken with 2 projects

### ISSUE THREAD

**Issue by Gama11** [SlavaRa/fdplugin-quicknavigate#93]
In the Recent Projects window, navigation with the up and down keys while the filter textfield has focus only works if there are 3 or more projects in the list. With 2, the up / down keys behave like left / right in the textfield, moving the caret.

**Comment by SlavaRa** [comment]
I fix it in the near future, sorry

**Comment by SlavaRa** [comment]
fixes https://github.com/SlavaRa/fdplugin-quicknavigate/releases/tag/2.6.22
