### ISSUE TITLE
Add support for themes

### ISSUE THREAD

**Issue by ylazy** [SlavaRa/fdplugin-quicknavigate#99]
It's a minor feature but it would be great if you could add support for FD themes on future.

Thank you for a great plug-in :)

**Comment by SlavaRa** [comment]
WIP

**Comment by SlavaRa** [comment]
WIP
(VsDark): 
![image](http://service.crazypanda.ru/v/clip2net/Q/w/CfpT5gunFt.png)
(SolarizedDark): 
![image](http://service.crazypanda.ru/v/clip2net/i/y/Bk6q7gZxbr.png)
(VsLight): 
![image](http://service.crazypanda.ru/v/clip2net/b/l/e8ycyY0GAl.png)

good?

**Comment by SlavaRa** [comment]
Please try https://github.com/SlavaRa/fdplugin-quicknavigate/releases/tag/2.7.266

**Comment by ylazy** [comment]
Thanks!
